### ISSUE TITLE
Github page URL

### ISSUE THREAD

**Issue by clodpheasant** [TiC-1/Week1_Project#2]
This is the address of our repo
https://tic-1.github.io/Week1_Project/

**Comment by matjack1** [comment]
@clodpheasant you can use the edit button in the home of the project:

![screenshot from 2018-02-08 11-56-35](https://user-images.githubusercontent.com/65402/35969457-221de1ee-0cc7-11e8-88a3-60c28f063bf6.png)

to add the URL of the Github pages website visible in the head of the project (together with a headline).
