### ISSUE TITLE
Quick code clean

### ISSUE THREAD

**Issue by matjack1** [TiC-1/Week1_Project#37]
A couple of things:
- remove commented out code
- try to better indent the code, both CSS and HTML. Hint: there's an automatic tool in Atom.

**Comment by matjack1** [comment]
You still have commented out code:
- https://github.com/TiC-1/Week1_Project/blob/master/style.css#L77
- https://github.com/TiC-1/Week1_Project/blob/master/index.html#L31

**Comment by clodpheasant** [comment]
closed for real
